# Generated by Django 2.2.2 on 2019-06-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anzeigen', '0002_auto_20190628_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anzeige',
            name='kategorie',
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
    ]
