# Generated by Django 2.2.2 on 2019-06-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anzeigen', '0003_auto_20190628_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.AddField(
            model_name='anzeige',
            name='kategorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anzeigen.Kategorie'),
        ),
    ]
